name = "fafa-resume"
compatibility_date = "2023-10-30"

[site]
bucket = "build"

[observability.logs]
enabled = true

# PDF文件的头部配置，确保正确下载
[[headers]]
for = "/*.pdf"
[headers.values]
"Content-Type" = "application/pdf"
"Content-Disposition" = "attachment"
"Cache-Control" = "public, max-age=31536000"
"X-Content-Type-Options" = "nosniff"



